### PR TITLE
pretty log

### LINKED ISSUE #17: append to logfile instead of overwriting
Issuing multiple zfsbud.sh commands sequentially, targeting the same logfile, results in only preserving the log of the last command. It does not append, but overwrite the already existing logfile. IMO it would be better to append, and use tools such as logrotate to deal with the growth of the logfile.

### PR DESCRIPTION
**Pull request by kapitainsky**
fixes #17 and add timestamp

### CODE REVIEW

**Comment by gbytedev** [comment]
@kapitainsky Thanks for this!

What do you think of making the time format more [international](https://ss64.com/dates.html), like `YYYY-MM-DD hh:mm:ss`?

Also, any issue with making it `### YYYY-MM-DD hh:mm:ss` instead of `*** YYYY-MM-DD hh:mm:ss` for easier grepping and better visual recognition (different to the "***" of other labels)?

**Comment by kapitainsky** [comment]
> What do you think of making the time format more [international](https://ss64.com/dates.html), like `YYYY-MM-DD hh:mm:ss`?
> 
> Also, any issue with making it `### YYYY-MM-DD hh:mm:ss` instead of `*** YYYY-MM-DD hh:mm:ss` for easier grepping and better visual recognition (different to the "***" of other labels)?

Good suggestion - will update in a moment

**Comment by kapitainsky** [comment]
Done

**Comment by gbytedev** [comment]
Thank you!

**Pull request merged**
